<?php $adwords_categories = array("Arts & Entertainment",
"Celebrities & Entertainment News",
"Comics & Animation",
"Anime & Manga",
"Cartoons",
"Comics",
"Entertainment Industry",
"Film & TV Industry",
"Film & TV Awards",
"Film & TV Production",
"Recording Industry",
"Music Awards",
"Record Labels",
"Events & Listings",
"Bars, Clubs & Nightlife",
"Concerts & Music Festivals",
"Event Ticket Sales",
"Expos & Conventions",
"Film Festivals",
"Food & Beverage Events",
"Live Sporting Events",
"Movie Listings & Theater Showtimes",
"Fun & Trivia",
"Flash-Based Entertainment",
"Fun Tests & Silly Surveys",
"Humor",
"Live Comedy",
"Political Humor",
"Spoofs & Satire",
"Movies",
"Action & Adventure Films",
"Martial Arts Films",
"Superhero Films",
"Western Films",
"Animated Films",
"Bollywood & South Asian Film",
"Classic Films",
"Silent Films",
"Comedy Films",
"Cult & Indie Films",
"DVD & Video Shopping",
"DVD & Video Rentals",
"Documentary Films",
"Drama Films",
"Family Films",
"Horror Films",
"Movie Memorabilia",
"Movie Reference",
"Movie Reviews & Previews",
"Musical Films",
"Romance Films",
"Science Fiction & Fantasy Films",
"Thriller, Crime & Mystery Films",
"Music & Audio",
"CD & Audio Shopping",
"Classical Music",
"Country Music",
"Dance & Electronic Music",
"Experimental & Industrial Music",
"Folk & Traditional Music",
"Jazz & Blues",
"Blues",
"Jazz",
"Music Art & Memorabilia",
"Music Education & Instruction",
"Music Equipment & Technology",
"DJ Resources & Equipment",
"Music Recording Technology",
"Musical Instruments",
"Drums & Percussion",
"Guitars",
"Pianos & Keyboards",
"Samples & Sound Libraries",
"Music Reference",
"Music Composition & Theory",
"Sheet Music",
"Song Lyrics & Tabs",
"Music Streams & Downloads",
"Music Videos",
"Pop Music",
"Radio",
"Podcasting",
"Talk Radio",
"Rock Music",
"Classic Rock & Oldies",
"Hard Rock & Progressive",
"Indie & Alternative Music",
"Metal (Music)",
"Punk (Music)",
"Soundtracks",
"Urban & Hip-Hop",
"Rap & Hip-Hop",
"Reggaeton",
"Soul & R&B",
"Vocals & Show Tunes",
"World Music",
"African Music",
"Arab & Middle Eastern Music",
"East Asian Music",
"Latin American Music",
"Brazilian Music",
"Latin Pop",
"Salsa & Tropical Music",
"Reggae & Caribbean Music",
"South Asian Music",
"Offbeat",
"Online Media",
"Online Image Galleries",
"Webcams & Virtual Tours",
"Performing Arts",
"Acting & Theater",
"Broadway & Musical Theater",
"Circus",
"Dance",
"Magic",
"Opera",
"TV & Video",
"Online Video",
"Web Series",
"TV Commercials",
"TV Guides & Reference",
"TV Networks & Stations",
"TV Shows & Programs",
"TV Comedies",
"TV Documentary & Nonfiction",
"TV Dramas",
"TV Crime & Legal Shows",
"TV Medical Shows",
"TV Soap Operas",
"TV Family-Oriented Shows",
"TV Game Shows",
"TV Reality Shows",
"TV Sci-Fi & Fantasy Shows",
"TV Talent & Variety Shows",
"TV Talk Shows",
"Visual Art & Design",
"Architecture",
"Art & Craft Supplies",
"Art Museums & Galleries",
"Arts Education",
"Design",
"Graphic Design",
"Industrial & Product Design",
"Interior Design",
"Painting",
"Photographic & Digital Arts",
"Sculpture",
"Autos & Vehicles",
"Bicycles & Accessories",
"BMX Bikes",
"Bike Accessories",
"Bike Frames",
"Bike Helmets & Protective Gear",
"Bike Parts & Repair",
"Cruiser Bikes",
"Cycling Apparel",
"Kid’s Bikes",
"Mountain Bikes",
"Road Bikes",
"Boats & Watercraft",
"Campers & RVs",
"Classic Vehicles",
"Commercial Vehicles",
"Cargo Trucks & Trailers",
"Custom & Performance Vehicles",
"Hybrid & Alternative Vehicles",
"Electric & Plug-In Vehicles",
"Microcars & City Cars",
"Motorcycles",
"Off-Road Vehicles",
"Personal Aircraft",
"Scooters & Mopeds",
"Trucks & SUVs",
"SUVs",
"Trucks",
"Vans & Minivans",
"Vehicle Brands",
"Acura",
"Audi",
"BMW",
"Bentley",
"Buick",
"Cadillac",
"Chevrolet",
"Chrysler",
"Citroën",
"Dodge",
"Ferrari",
"Fiat",
"Alfa Romeo",
"Ford",
"GM-Daewoo",
"GMC",
"Honda",
"Hummer",
"Hyundai",
"Isuzu",
"Jaguar",
"Jeep",
"Kia",
"Lamborghini",
"Land Rover",
"Lexus",
"Lincoln",
"Maserati",
"Mazda",
"Mercedes-Benz",
"Mercury",
"Mini",
"Mitsubishi",
"Nissan",
"Infiniti",
"Peugeot",
"Pontiac",
"Porsche",
"Renault-Samsung",
"Rolls-Royce",
"SEAT",
"Saab",
"Saturn",
"Subaru",
"Suzuki",
"Toyota",
"Scion",
"Vauxhall-Opel",
"Volkswagen",
"Volvo",
"Vehicle Codes & Driving Laws",
"Vehicle & Traffic Safety",
"Vehicle Licensing & Registration",
"Driving Instruction & Driver Education",
"Vehicle Maintenance",
"Vehicle Parts & Accessories",
"Auto Exterior",
"Auto Interior",
"Engine & Transmission",
"Vehicle Fuels & Lubricants",
"Vehicle Wheels & Tires",
"Vehicle Shopping",
"Fuel Economy & Gas Prices",
"Vehicle Specs, Reviews & Comparisons",
"Vehicle Shows",
"Beauty & Fitness",
"Beauty Pageants",
"Body Art",
"Cosmetology & Beauty Professionals",
"Face & Body Care",
"Hygiene & Toiletries",
"Make-Up & Cosmetics",
"Perfumes & Fragrances",
"Skin & Nail Care",
"Fashion & Style",
"Fashion Designers & Collections",
"Fashion Modeling",
"Fitness",
"Bodybuilding",
"Fitness Equipment & Accessories",
"Fitness Instruction & Personal Training",
"Gyms & Health Clubs",
"Yoga & Pilates",
"Hair Care",
"Spas & Beauty Services",
"Massage Therapy",
"Books & Literature",
"Book Retailers",
"Children’s Literature",
"E-Books",
"Fan Fiction",
"Literary Classics",
"Magazines",
"Poetry",
"Writers Resources",
"Business & Industrial",
"Advertising & Marketing",
"Brand Management",
"Marketing",
"Promotional Items & Corporate Gifts",
"Public Relations",
"Sales",
"Telemarketing",
"Aerospace & Defense",
"Defense Industry",
"Space Technology",
"Agriculture & Forestry",
"Agricultural Equipment",
"Aquaculture",
"Crops & Seed",
"Farms & Ranches",
"Food Production",
"Forestry",
"Horticulture",
"Livestock",
"Automotive Industry",
"Business Education",
"Business Finance",
"Commercial Lending",
"Investment Banking",
"Risk Management",
"Venture Capital",
"Business Operations",
"Business Plans & Presentations",
"Human Resources",
"Compensation & Benefits",
"Corporate Training",
"Payroll Services",
"Recruitment & Staffing",
"Management",
"Business Process",
"Project Management",
"Strategic Planning",
"Supply Chain Management",
"Business Services",
"Consulting",
"Corporate Events",
"Trade Fairs & Industry Shows",
"E-Commerce Services",
"Merchant Services & Payment Systems",
"Fire & Security Services",
"Knowledge Management",
"Office Services",
"Office & Facilities Management",
"Office Supplies",
"Office Furniture",
"Outsourcing",
"Physical Asset Management",
"Quality Control & Tracking",
"Signage",
"Writing & Editing Services",
"Chemicals Industry",
"Agrochemicals",
"Cleaning Agents",
"Coatings & Adhesives",
"Dyes & Pigments",
"Plastics & Polymers",
"Construction & Maintenance",
"Building Materials & Supplies",
"Nails Screws & Fasteners",
"Plumbing Fixtures & Equipment",
"Wood & Plastics",
"Civil Engineering",
"Construction Consulting & Contracting",
"Urban & Regional Planning",
"Energy & Utilities",
"Electricity",
"Nuclear Energy",
"Oil & Gas",
"Renewable & Alternative Energy",
"Hydropower",
"Solar Power",
"Wind Power",
"Waste Management",
"Waste Recycling",
"Water Supply & Treatment",
"Hospitality Industry",
"Event Planning",
"Food Service",
"Restaurant Supply",
"Industrial Materials & Equipment",
"Fluid Handling",
"Valves Hoses & Fittings",
"Generators",
"Heavy Machinery",
"Manufacturing",
"Factory Automation",
"Metals & Mining",
"Precious Metals",
"Pharmaceuticals & Biotech",
"Printing & Publishing",
"Document & Printing Services",
"Business Cards & Stationary",
"Professional & Trade Associations",
"Retail Trade",
"Retail Equipment & Technology",
"Small Business",
"Business Formation",
"Home Office",
"MLM & Business Opportunities",
"Textiles & Nonwovens",
"Transportation & Logistics",
"Aviation",
"Distribution & Logistics",
"Freight & Trucking",
"Import & Export",
"Mail & Package Delivery",
"Couriers & Messengers",
"Maritime Transport",
"Moving & Relocation",
"Packaging",
"Parking",
"Public Storage",
"Rail Transport",
"Urban Transport",
"Warehousing",
"Computers & Electronics",
"CAD & CAM",
"Computer Hardware",
"Computer Components",
"Chips & Processors",
"Computer Memory",
"Sound & Video Cards",
"Computer Drives & Storage",
"CD & DVD Drives & Burners",
"CD & DVD Storage Media",
"Data Backup & Recovery",
"Flash Drives & Memory Cards",
"Hard Drives",
"Memory Card Readers",
"Network Storage",
"Computer Peripherals",
"Computer Monitors & Displays",
"Input Devices",
"Printers, Copiers & Fax",
"Copiers",
"Fax Machines",
"Ink & Toner",
"Printers",
"Scanners",
"Computer Servers",
"Desktop Computers",
"Hardware Modding & Tuning",
"Laptops & Notebooks",
"Tablet PCs",
"Computer Security",
"Antivirus & Malware",
"Network Security",
"Consumer Electronics",
"Audio Equipment",
"Headphones",
"Speakers",
"Stereo Systems & Components",
"Camera & Photo Equipment",
"Binoculars, Telescopes & Optical Devices",
"Cameras & Camcorders",
"Camcorders",
"Camera Lenses",
"Cameras",
"Car Electronics",
"Car Audio",
"Car Video",
"Electronic Accessories",
"GPS & Navigation",
"Gadgets & Portable Electronics",
"E-Book Readers",
"MP3 & Portable Media Players",
"PDAs & Handhelds",
"Game Systems & Consoles",
"Handheld Game Consoles",
"Nintendo",
"Sony PlayStation",
"Xbox",
"TV & Video Equipment",
"DVRs & Set-Top Boxes",
"Home Theater Systems",
"Projectors & Screens",
"Televisions",
"HDTVs",
"LCD TVs",
"Plasma TVs",
"Projection TVs",
"Video Players & Recorders",
"Blu-Ray Players & Recorders",
"DVD Players & Recorders",
"Electronics & Electrical",
"Data Sheets & Electronics Reference",
"Electromechanical Devices",
"Electronic Components",
"Optoelectronics & Fiber",
"Power Supplies",
"Test & Measurement",
"Enterprise Technology",
"Customer Relationship Management (CRM)",
"Data Management",
"Enterprise Resource Planning (ERP)",
"Networking",
"Data Formats & Protocols",
"Network Monitoring & Management",
"Networking Equipment",
"VPN & Remote Access",
"Programming",
"C & C++",
"Development Tools",
"Java (Programming Language)",
"Scripting Languages",
"Windows & .NET",
"Software",
"Business & Productivity Software",
"Accounting & Financial Software",
"Calendar & Scheduling Software",
"Presentation Software",
"Project Management Software",
"Spreadsheet Software",
"Word Processing Software",
"Device Drivers",
"Educational Software",
"Freeware & Shareware",
"Internet Software",
"Content Management",
"Download Managers",
"Internet Clients & Browsers",
"Proxying & Filtering",
"Multimedia Software",
"Audio & Music Software",
"Audio Files Formats & Codecs",
"Desktop Publishing",
"Fonts",
"Graphics & Animation Software",
"Media Players",
"Photo & Video Software",
"Video File Formats & Codecs",
"Open Source",
"Operating Systems",
"Linux & Unix",
"Mac OS",
"Mobile OS",
"Android OS",
"Apple iOS",
"BlackBerry OS",
"Symbian OS",
"Windows Mobile OS",
"Windows OS",
"Software Utilities",
"Finance",
"Accounting & Auditing",
"Billing & Invoicing",
"Bookkeeping",
"Tax Preparation & Planning",
"Banking",
"ATMs & Branch Locations",
"Debit & Checking Services",
"Money Transfer & Wire Services",
"Savings Accounts",
"Credit & Lending",
"Credit Cards",
"Credit Reporting & Monitoring",
"Loans",
"Home Financing",
"Home Equity Loans & Lines of Credit",
"Home Refinancing",
"Mortgages",
"Personal Loans",
"Student Loans & College Financing",
"Vehicle Financing",
"Auto Financing",
"Financial Planning & Management",
"Asset & Portfolio Management",
"Inheritance & Estate Planning",
"Retirement & Pension",
"Grants, Scholarships & Financial Aid",
"Government Grants",
"Study Grants & Scholarships",
"Insurance",
"Health Insurance",
"Home Insurance",
"Life Insurance",
"Travel Insurance",
"Vehicle Insurance",
"Vehicle Auto Insurance",
"Investing",
"Brokerages & Day Trading",
"Commodities & Futures Trading",
"Currencies & Foreign Exchange",
"Derivatives",
"Funds",
"Exchange Traded Funds",
"Hedge Funds",
"Mutual Funds",
"Real Estate Investment Trusts",
"Socially Responsible Investing",
"Stocks & Bonds",
"Bonds",
"Exchanges",
"Food & Drink",
"Beverages",
"Bottled Water",
"Coffee & Tea",
"Coffee",
"Tea",
"Juice",
"Soft Drinks",
"Cooking & Recipes",
"BBQ & Grilling",
"Cuisines",
"East Asian Cuisine",
"Chinese Cuisine",
"Japanese Cuisine",
"Korean Cuisine",
"Eastern European Cuisine",
"French Cuisine",
"German Cuisine",
"Latin American Cuisine",
"Caribbean Cuisine",
"Mexican Cuisine",
"South American Cuisine",
"Mediterranean Cuisine",
"Greek Cuisine",
"Italian Cuisine",
"Spanish Cuisine",
"Middle Eastern Cuisine",
"North American Cuisine",
"South Asian Cuisine",
"Indian Cuisine",
"Southeast Asian Cuisine",
"Thai Cuisine",
"Vietnamese Cuisine",
"Vegetarian Cuisine",
"Culinary Training",
"Desserts",
"Healthy Eating",
"Salads",
"Soups & Stews",
"Food",
"Baked Goods",
"Breakfast Foods",
"Candy & Sweets",
"Condiments & Dressings",
"Cooking Fats & Oils",
"Dairy & Eggs",
"Cheese",
"Fruits & Vegetables",
"Gourmet & Specialty Foods",
"Grains & Pasta",
"Herbs & Spices",
"Jams, Jellies & Preserves",
"Meat & Seafood",
"Beef",
"Fish & Seafood",
"Pork",
"Poultry",
"Organic & Natural Foods",
"Snack Foods",
"Food & Grocery Delivery",
"Food & Grocery Retailers",
"Bakeries",
"Butchers",
"Convenience Stores",
"Delicatessens",
"Farmers’ Markets",
"Restaurants",
"Catering",
"Dining Guides",
"Fast Food",
"Burgers",
"Fine Dining",
"Pizzerias",
"Games",
"Arcade & Coin-Op Games",
"Board Games",
"Board Chess & Abstract Strategy Games",
"Board Miniatures & Wargaming",
"Card Games",
"Card Collectible Card Games",
"Computer & Video Games",
"Action & Platform Games",
"Adventure Games",
"Casual Games",
"Driving & Racing Games",
"Fighting Games",
"Gaming Media & Reference",
"Game Cheats & Hints",
"Music & Dance Games",
"Shooter Games",
"Simulation Games",
"Business & Tycoon Games",
"City Building Games",
"Life Simulation Games",
"Vehicle Simulators",
"Sports Games",
"Sports Management Games",
"Strategy Games",
"Video Game Development",
"Video Game Emulation",
"Video Game Retailers",
"Dice Games",
"Educational Games",
"Family-Oriented Games & Activities",
"Drawing & Coloring",
"Online Games",
"Online Massive Multiplayer",
"Party Games",
"Puzzles & Brainteasers",
"Roleplaying Games",
"Table Games",
"Billiards",
"Table Table Tennis",
"Tile Games",
"Word Games",
"Hobbies & Leisure",
"Clubs & Organizations",
"Fraternal Orders & Service Clubs",
"Youth Organizations & Resources",
"Contests, Awards & Prizes",
"Crafts",
"Ceramics & Pottery",
"Fiber & Textile Arts",
"Outdoors",
"Equestrian",
"Fishing",
"Hiking & Camping",
"Hunting & Shooting",
"Paintball",
"Radio Control & Modeling",
"Model Trains & Railroads",
"Recreational Aviation",
"Special Occasions",
"Holidays & Seasonal Events",
"Birthdays & Name Days",
"Carnival & Mardi Gras",
"Halloween & October 31st",
"New Year",
"Thanksgiving",
"Valentine’s Day",
"Weddings",
"Water Activities",
"Boating",
"Diving & Underwater Activities",
"Surf & Swim",
"Home & Garden",
"Bed & Bath",
"Bathroom",
"Bedroom",
"Bedding & Bed Linens",
"Beds & Headboards",
"Mattresses",
"Domestic Services",
"Cleaning Supplies & Services",
"Gardening & Landscaping",
"HVAC & Climate Control",
"Home Appliances",
"Water Filters & Purifiers",
"Home Furnishings",
"Clocks",
"Lamps & Lighting",
"Rugs & Carpets",
"Sofas & Chairs",
"Home Improvement",
"Construction & Power Tools",
"Doors & Windows",
"Flooring",
"House Painting & Finishing",
"Locks & Locksmiths",
"Plumbing",
"Roofing",
"Home Storage & Shelving",
"Homemaking & Interior Decor",
"Kitchen & Dining",
"Cookware & Diningware",
"Cutlery & Cutting Accessories",
"Major Kitchen Appliances",
"Dishwashers",
"Kitchen Hoods & Vents",
"Microwaves",
"Ranges, Cooktops & Ovens",
"Refrigerators & Freezers",
"Small Kitchen Appliances",
"Blenders",
"Bread Makers",
"Coffee & Espresso Makers",
"Food Processors",
"Toasters & Toaster Ovens",
"Laundry",
"Nursery & Playroom",
"Pest Control",
"Swimming Pools & Spas",
"Yard & Patio",
"Internet & Telecom",
"Communications Equipment",
"Radio Equipment",
"Email & Messaging",
"Spam & Email Filtering",
"Text & Instant Messaging",
"Voice & Video Chat",
"Mobile & Wireless",
"Mobile & Wireless Accessories",
"Bluetooth Accessories",
"Mobile Apps & Add-Ons",
"Android Apps",
"Ringtones & Mobile Themes",
"iOS Apps",
"Mobile Phones",
"Smart Phones",
"Search Engines",
"People Search",
"Service Providers",
"Cable & Satellite Providers",
"ISPs",
"Internet Cafes",
"Phone Service Providers",
"Phone Calling Cards",
"Teleconferencing",
"Web Apps & Online Tools",
"Web Portals",
"Web Services",
"Affiliate Programs",
"Hosted Data Storage",
"Search Engine Optimization & Marketing",
"Web Design & Development",
"Web Hosting & Domain Registration",
"Web Stats & Analytics",
"Jobs & Education",
"Education",
"Academic Conferences & Publications",
"Alumni & Reunions",
"Colleges & Universities",
"Fraternities, Sororities & Student Societies",
"Distance Learning",
"Early Childhood Education",
"Early Childhood Preschool",
"Homeschooling",
"Primary & Secondary Schooling (K-12)",
"Special Education",
"Standardized & Admissions Tests",
"Study Abroad",
"Teaching & Classroom Resources",
"Lesson Plans",
"School Supplies & Classroom Equipment",
"Training & Certification",
"Vocational & Continuing Education",
"Vocational & Continuing Computer Education",
"Internships",
"Jobs",
"Career Resources & Planning",
"Job Listings",
"Accounting & Finance Jobs",
"Clerical & Administrative Jobs",
"Education Jobs",
"Executive & Management Jobs",
"Government & Public Sector Jobs",
"Health & Medical Jobs",
"IT & Technical Jobs",
"Legal Jobs",
"Retail Jobs",
"Sales & Marketing Jobs",
"Temporary & Seasonal Jobs",
"Resumes & Portfolios",
"Law & Government",
"Government",
"Courts & Judiciary",
"Embassies & Consulates",
"Executive Branch",
"Government Agencies",
"Government Contracting & Procurement",
"Intelligence & Counterterrorism",
"Legislative Branch",
"Lobbying",
"Multilateral Organizations",
"Public Finance",
"Public Policy",
"Royalty",
"State & Local Government",
"Visa & Immigration",
"Legal",
"Business & Corporate Law",
"Intellectual Property",
"Labor & Employment Law",
"Legal Education",
"Legal Services",
"Product Liability",
"Military",
"Air Force",
"Army",
"Marines",
"Navy",
"Veterans",
"Public Safety",
"Crime & Justice",
"Corporate & Financial Crime",
"Gangs & Organized Crime",
"Emergency Services",
"Law Enforcement",
"Security Products & Services",
"News",
"Broadcast & Network News",
"Business News",
"Company News",
"Company Company Earnings",
"Company Mergers & Acquisitions",
"Economy News",
"Financial Markets",
"Fiscal Policy News",
"Gossip & Tabloid News",
"Scandals & Investigations",
"Health News",
"Journalism & News Industry",
"Local News",
"Newspapers",
"Politics",
"Campaigns & Elections",
"Sports News",
"Technology News",
"Weather",
"World News",
"Online Communities",
"Blogging Resources & Services",
"Microblogging",
"Dating & Personals",
"Photo Rating Sites",
"Feed Aggregation & Social Bookmarking",
"File Sharing & Hosting",
"Forum & Chat Providers",
"Online Goodies",
"Clip Art & Animated GIFs",
"Skins Themes & Wallpapers",
"Social Network Apps & Add-Ons",
"Online Journals & Personal Sites",
"Photo & Video Sharing",
"Photo & Image Sharing",
"Video Sharing",
"Social Networks",
"Virtual Worlds",
"People & Society",
"Family & Relationships",
"Etiquette",
"Family",
"Ancestry & Genealogy",
"Baby & Pet Names",
"Parenting",
"Adoption",
"Babies & Toddlers",
"Baby & Toddler Toys",
"Baby Care & Hygiene",
"Baby Food & Formula",
"Child Care",
"Youth Camps",
"Friendship",
"Marriage",
"Romance",
"Men’s Interests",
"Social Issues & Advocacy",
"Charity & Philanthropy",
"Drug Laws & Policy",
"Ethics",
"Green Living & Environmental Issues",
"Immigration Policy & Border Issues",
"Privacy Issues",
"Work & Labor Issues",
"Unions & Labor Movement",
"Social Sciences",
"Anthropology",
"Archaeology",
"Communications & Media Studies",
"Public Speaking",
"Demographics",
"Economics",
"International Relations",
"Psychology",
"Subcultures & Niche Interests",
"Goth Subculture",
"Science Fiction & Fantasy",
"Women’s Interests",
"Pets & Animals",
"Animal Products & Services",
"Animal Welfare",
"Pet Food & Supplies",
"Veterinarians",
"Pets",
"Birds",
"Cats",
"Dogs",
"Exotic Pets",
"Fish & Aquaria",
"Horses",
"Rabbits & Rodents",
"Reptiles & Amphibians",
"Wildlife",
"Real Estate",
"Apartments & Residential Rentals",
"Commercial & Investment Real Estate",
"Property Development",
"Property Inspections & Appraisals",
"Property Management",
"Real Estate Agencies",
"Real Estate Listings",
"Timeshares & Vacation Properties",
"Reference",
"Directories & Listings",
"Business & Personal Listings",
"General Reference",
"Biographies & Quotations",
"Calculators & Reference Tools",
"Dictionaries & Encyclopedias",
"Educational Resources",
"Forms Guides & Templates",
"Legal Forms",
"How-To, DIY & Expert Content",
"Public Records",
"Time & Calendars",
"Geographic Reference",
"City & Local Guides",
"Maps",
"Traffic & Public Transit",
"Humanities",
"History",
"Military History",
"Myth & Folklore",
"Philosophy",
"Language Resources",
"Foreign Language Resources",
"Foreign Language Study",
"Translation Tools & Resources",
"Libraries & Museums",
"Libraries",
"Museums",
"Technical Reference",
"Science",
"Astronomy",
"Biological Sciences",
"Anatomy",
"Flora & Fauna",
"Insects & Entomology",
"Neuroscience",
"Chemistry",
"Computer Science",
"Distributed & Parallel Computing",
"Machine Learning & Artificial Intelligence",
"Earth Sciences",
"Atmospheric Science",
"Geology",
"Paleontology",
"Water & Marine Sciences",
"Ecology & Environment",
"Climate Change & Global Warming",
"Engineering & Technology",
"Robotics",
"Mathematics",
"Statistics",
"Physics",
"Scientific Equipment",
"Scientific Institutions",
"Shopping",
"Antiques & Collectibles",
"Apparel",
"Apparel Services",
"Athletic Apparel",
"Casual Apparel",
"T-Shirts",
"Children’s Clothing",
"Clothing Accessories",
"Gems & Jewelry",
"Rings",
"Handbags & Purses",
"Watches",
"Costumes",
"Eyewear",
"Sunglasses",
"Footwear",
"Athletic Shoes",
"Boots",
"Casual Shoes",
"Formal Wear",
"Bridal Wear",
"Headwear",
"Men’s Clothing",
"Outerwear",
"Sleepwear",
"Suits & Business Attire",
"Swimwear",
"Undergarments",
"Uniforms & Workwear",
"Women’s Clothing",
"Dresses",
"Skirts",
"Auctions",
"Classifieds",
"Consumer Resources",
"Consumer Advocacy & Protection",
"Coupons & Discount Offers",
"Customer Services",
"Loyalty Cards & Programs",
"Technical Support",
"Warranties & Service Contracts",
"Identity Theft & Protection",
"Product Reviews & Price Comparisons",
"Price Comparisons",
"Discount & Outlet Stores",
"Entertainment Media",
"Entertainment Media Rentals",
"Gifts & Special Event Items",
"Cards & Greetings",
"Custom & Personalized Items",
"Flowers",
"Gifts",
"Party & Holiday Supplies",
"Green & Eco-Friendly Shopping",
"Luxury Goods",
"Mass Merchants & Department Stores",
"Photo & Video Services",
"Stock Photography",
"Shopping Portals & Search Engines",
"Swap Meets & Outdoor Markets",
"Toys",
"Action Figures",
"Building Toys",
"Die-cast & Toy Vehicles",
"Dolls & Accessories",
"Outdoor Toys & Play Equipment",
"Puppets",
"Ride-On Toys & Wagons",
"Stuffed Toys",
"Wholesalers & Liquidators",
"Sports",
"College Sports",
"Combat Sports",
"Boxing",
"Martial Arts",
"Wrestling",
"Extreme Sports",
"Fantasy Sports",
"Individual Sports",
"Bowling",
"Cycling",
"Golf",
"Gymnastics",
"Racquet Sports",
"Tennis",
"Running & Walking",
"Skate Sports",
"Track & Field",
"Motor Sports",
"Auto Racing",
"Motorcycle Racing",
"Sport Scores & Statistics",
"Sporting Goods",
"American Football Equipment",
"Baseball Equipment",
"Basketball Equipment",
"Bowling Equipment",
"Combat Sports Equipment",
"Boxing Gloves & Gear",
"Martial Arts Equipment",
"Cricket Equipment",
"Equestrian Equipment & Tack",
"Golf Equipment",
"Gymnastics Equipment",
"Hockey Equipment",
"Ice Skating Equipment",
"Roller Skating & Rollerblading Equipment",
"Skateboarding Equipment",
"Soccer Equipment",
"Sports Memorabilia",
"Squash & Racquetball Equipment",
"Table Tennis Equipment",
"Tennis Equipment",
"Volleyball Equipment",
"Water Sports Equipment",
"Winter Sports Equipment",
"Skiing Equipment",
"Snowboarding Gear",
"Sports Coaching & Training",
"Team Sports",
"American Football",
"Australian Football",
"Baseball",
"Basketball",
"Cheerleading",
"Cricket",
"Handball",
"Hockey",
"Rugby",
"Soccer",
"Volleyball",
"Water Sports",
"Surfing",
"Swimming",
"Winter Sports",
"Ice Skating",
"Skiing & Snowboarding",
"World Sports Competitions",
"Olympics",
"Travel",
"Air Travel",
"Airport Parking & Transportation",
"Bus & Rail",
"Car Rental & Taxi Services",
"Carpooling & Vehicle Sharing",
"Cruises & Charters",
"Hotels & Accommodations",
"Luggage & Travel Accessories",
"Specialty Travel",
"Adventure Travel",
"Agritourism",
"Ecotourism",
"Sightseeing Tours",
"Vineyards & Wine Tourism",
"Tourist Destinations",
"Beaches & Islands",
"Historical Sites & Buildings",
"Lakes & Rivers",
"Mountain & Ski Resorts",
"Regional Parks & Gardens",
"Theme Parks",
"Zoos-Aquariums-Preserves",
"Travel Agencies & Services",
"Tourist Boards & Visitor Centers",
"Vacation Offers",
"Travel Guides & Travelogues",
"World Localities",
"Africa",
"Eastern Africa",
"Ethiopia",
"Kenya",
"Nairobi",
"Madagascar",
"Malawi",
"Mozambique",
"Rwanda",
"Somalia",
"Tanzania",
"Uganda",
"Zambia",
"Zimbabwe",
"Harare",
"Middle Africa",
"Angola",
"Cameroon",
"Chad",
"Congo (DR)",
"Kinshasa",
"Northern Africa",
"Algeria",
"Egypt",
"Cairo",
"Libya",
"Morocco",
"Sudan",
"Tunisia",
"Southern Africa",
"Botswana",
"South Africa",
"Cape Town",
"Johannesburg",
"Western Africa",
"Burkina Faso",
"Côte d’Ivoire",
"Ghana",
"Mali",
"Niger",
"Nigeria",
"Lagos",
"Senegal",
"Asia",
"Central Asia",
"Kazakhstan",
"Kyrgyzstan",
"Tajikistan",
"Turkmenistan",
"Uzbekistan",
"East Asia",
"China",
"Eastern China",
"Jiangsu",
"Nanjing",
"Shanghai",
"Zhejiang",
"Hangzhou",
"North Central China",
"Beijing",
"Hebei",
"Henan",
"Inner Mongolia",
"Shandong",
"Shanxi",
"Tianjin",
"Northeast China",
"Heilongjiang",
"Harbin",
"Jilin",
"Changchun",
"Liaoning",
"Shenyang",
"Northwest China",
"Gansu",
"Ningxia",
"Qinghai",
"Shaanxi",
"Xi’an",
"Xinjiang",
"South Central China",
"Anhui",
"Chongqing",
"Hubei",
"Wuhan",
"Hunan",
"Jiangxi",
"Sichuan",
"Southeast China",
"Fujian",
"Guangdong",
"Dongguan",
"Guangzhou",
"Shenzhen",
"Hainan",
"Southwest China",
"Guangxi",
"Guizhou",
"Tibet",
"Yunnan",
"Hong Kong",
"Japan",
"Chubu",
"Aichi",
"Nagoya",
"Fukui",
"Gifu",
"Ishikawa",
"Nagano",
"Niigata",
"Shizuoka",
"Toyama",
"Yamanashi",
"Chugoku",
"Hiroshima",
"Okayama",
"Shimane",
"Tottori",
"Yamaguchi",
"Hokkaido",
"Sapporo",
"Kansai",
"Hyogo",
"Kobe",
"Kyoto",
"Mie",
"Nara",
"Osaka",
"Shiga",
"Wakayama",
"Kanto",
"Chiba",
"Gunma",
"Ibaraki",
"Kanagawa",
"Kawasaki",
"Yokohama",
"Saitama",
"Tochigi",
"Tokyo",
"Kyushu",
"Fukuoka",
"Kagoshima",
"Kumamoto",
"Miyazaki",
"Nagasaki",
"Oita",
"Saga",
"Okinawa",
"Shikoku",
"Ehime",
"Kagawa",
"Kochi",
"Tokushima",
"Tohoku",
"Akita",
"Aomori",
"Fukushima",
"Iwate",
"Miyagi",
"Sendai",
"Yamagata",
"Macau",
"Mongolia",
"North Korea",
"South Korea",
"Gangwon",
"Gyeonggi",
"Incheon",
"Jeju",
"North Chungcheong",
"North Gyeongsang",
"Daegu",
"North Jeolla",
"Seoul",
"South Chungcheong",
"Daejeon",
"South Gyeongsang",
"Busan",
"Ulsan",
"South Jeolla",
"Gwangju",
"Taiwan",
"Hsinchu",
"Kaohsiung",
"Taichung",
"Tainan",
"Taipei",
"Russia & CIS",
"Caucasus",
"Armenia",
"Azerbaijan",
"Georgia",
"Russian Federation",
"Far Eastern Russia",
"North Caucasian District",
"Northwestern Russia",
"Saint Petersburg",
"Russian Central District",
"Moscow",
"Russian Southern District",
"Siberian Federal District",
"Urals District",
"Volga District",
"South Asia",
"Afghanistan",
"Bangladesh",
"Bhutan",
"India",
"East India",
"Bihar",
"Chhattisgarh",
"Orissa",
"West Bengal",
"Kolkata",
"North India",
"Delhi",
"Madhya Pradesh",
"Punjab (India)",
"Uttar Pradesh",
"Agra",
"Northeast India",
"South India",
"Andhra Pradesh",
"Hyderabad",
"Karnataka",
"Bangalore",
"Kerala",
"Tamil Nadu",
"Chennai",
"West India",
"Goa",
"Gujarat",
"Maharashtra",
"Mumbai",
"Rajasthan",
"Jaipur",
"Indian Ocean Islands",
"Maldives",
"Réunion",
"Nepal",
"Pakistan",
"Karachi",
"Lahore",
"Sri Lanka",
"Southeast Asia",
"Brunei",
"Cambodia",
"East Timor",
"Indonesia",
"Java (Indonesia)",
"Jakarta",
"Kalimantan",
"Maluku Islands",
"Nusa Tenggara",
"Bali",
"Sulawesi",
"Sumatra",
"Western New Guinea",
"Laos",
"Malaysia",
"Kuala Lumpur",
"Myanmar",
"Philippines",
"Cebu",
"Manila",
"Singapore",
"Thailand",
"Bangkok",
"Chiang Mai",
"Pattaya",
"Southern Thailand",
"Southern Phuket",
"Viet Nam",
"Hanoi",
"Ho Chi Minh City",
"West Asia",
"Bahrain",
"Iran",
"Iraq",
"Israel",
"Jerusalem",
"Palestine",
"Tel Aviv",
"Jordan",
"Kuwait",
"Lebanon",
"Oman",
"Qatar",
"Saudi Arabia",
"Syria",
"Turkey",
"Aegean Turkey",
"Izmir",
"Muğla",
"Bodrum",
"Pamukkale",
"Black Sea Turkey",
"Central Anatolia",
"Ankara",
"Cappadocia",
"Konya",
"Eastern Anatolia",
"Marmara Region",
"Bursa",
"Istanbul",
"Mediterranean Turkey",
"Adana",
"Antalya",
"Mersin",
"Southeastern Anatolia",
"United Arab Emirates",
"Yemen",
"Europe",
"Central & Eastern Europe",
"Austria",
"Vienna",
"Baltics",
"Estonia",
"Latvia",
"Lithuania",
"Czech Republic",
"Prague",
"Eastern Europe",
"Belarus",
"Moldova",
"Ukraine",
"Crimea",
"Kiev",
"Germany",
"Baden-Wuerttemberg",
"Bavaria",
"Munich",
"Berlin",
"Brandenburg",
"Bremen",
"Hamburg",
"Hesse",
"Frankfurt",
"Lower Saxony",
"Mecklenburg-Vorpommern",
"North Rhine-Westphalia",
"Cologne",
"Duesseldorf",
"Essen (Ruhr Area)",
"Rhineland-Palatinate",
"Saarland",
"Saxony",
"Saxony-Anhalt",
"Schleswig-Holstein",
"Thuringia",
"Hungary",
"Budapest",
"Liechtenstein",
"Poland",
"Katowice (Upper Silesian)",
"Krakow",
"Warsaw",
"Wroclaw",
"Łódź",
"Slovakia",
"Slovenia",
"Switzerland",
"Geneva",
"Zurich",
"Mediterranean Europe",
"Cyprus",
"Italy",
"Abruzzo",
"Aosta Valley",
"Basilicata",
"Calabria",
"Campania",
"Naples",
"Salerno & Amalfi Coast",
"Emilia-Romagna",
"Friuli-Venezia Giulia",
"Lazio",
"Rome",
"Liguria",
"Genoa",
"Lombardy",
"Milan",
"Marche",
"Molise",
"Piedmont",
"Turin",
"Puglia",
"Bari",
"Sardinia",
"Sicily",
"Palermo",
"Trentino-Alto Adige",
"Tuscany",
"Florence",
"Umbria",
"Veneto",
"Venice",
"Malta",
"Monaco",
"Portugal",
"Azores & Madeira",
"Lisbon",
"Porto",
"San Marino",
"Spain",
"Andalucia",
"Cádiz",
"Málaga",
"Seville",
"Aragon",
"Asturias",
"Balearic Islands",
"Basque Country",
"Canary Islands",
"Cantabria",
"Castile and León",
"Castile-La Mancha",
"Catalonia",
"Barcelona",
"Extremadura",
"Galicia",
"Madrid",
"Murcia",
"Valencian Community",
"Valencia",
"Vatican City",
"Nordic Countries",
"Denmark",
"Copenhagen",
"Finland",
"Helsinki",
"Greenland",
"Iceland",
"Norway",
"Oslo",
"Sweden",
"Stockholm",
"Southeastern Europe",
"Albania",
"Bosnia and Herzegovina",
"Bulgaria",
"Croatia",
"Greece",
"Aegean Islands",
"Athens",
"Crete",
"Kosovo",
"Montenegro",
"Republic of Macedonia",
"Romania",
"Bucharest",
"Serbia",
"Western Europe",
"Andorra",
"Benelux",
"Belgium",
"Brussels",
"Luxembourg",
"Netherlands",
"Amsterdam",
"Rotterdam",
"France",
"Central France",
"Auvergne",
"Centre",
"Limousin",
"East France",
"Alsace",
"Strasbourg",
"Burgundy",
"Champagne-Ardenne",
"Franche-Comté",
"Lorraine",
"French Overseas (DOM-TOM)",
"North France",
"Lower Normandy",
"Nord-Pas-de-Calais",
"Lille",
"Picardy",
"Upper Normandy",
"South East France",
"Corsica",
"Provence-Alpes-Côte d’Azur",
"Marseille",
"Nice",
"Rhône-Alpes",
"Lyon",
"South West France",
"Aquitaine",
"Bordeaux",
"Languedoc-Roussillon",
"Montpellier",
"Midi-Pyrénées",
"Toulouse",
"West France",
"Brittany",
"Rennes",
"Pays de la Loire",
"Nantes",
"Poitou-Charentes",
"Île-de-France",
"Paris",
"Ireland",
"Dublin",
"United Kingdom",
"England",
"East Midlands",
"East of England",
"London (UK)",
"North East England",
"North West England",
"Liverpool",
"Manchester",
"South East England",
"South West England",
"Bristol",
"West Midlands",
"Birmingham (UK)",
"Yorkshire",
"Leeds-Bradford",
"Sheffield",
"Northern Ireland",
"Scotland",
"Edinburgh",
"Glasgow",
"Wales",
"Latin America",
"Caribbean",
"Antigua & Barbuda",
"Aruba, Bonaire & Curaçao",
"Bahamas",
"Barbados",
"Cayman Islands",
"Cuba",
"Dominica",
"Dominican Republic",
"Grenada",
"Guadeloupe",
"Haiti",
"Jamaica",
"Martinique",
"Puerto Rico",
"Saint Kitts & Nevis",
"Saint Lucia",
"Saint Vincent & Grenadines",
"Trinidad & Tobago",
"Virgin Islands",
"Central America",
"Belize",
"Costa Rica",
"El Salvador",
"Guatemala",
"Honduras",
"Mexico",
"Baja California",
"Los Cabos",
"Tijuana",
"Central Mexico",
"Cuernavaca (Morelos)",
"Guanajuato",
"Mexico City",
"Mexico State",
"Puebla",
"Veracruz",
"Northern Mexico",
"Chihuahua",
"Nuevo León",
"Monterrey",
"Tamaulipas",
"Pacific Coast (Mexico)",
"Chiapas",
"Guerrero",
"Acapulco",
"Jalisco",
"Guadalajara",
"Puerto Vallarta",
"Michoacán",
"Oaxaca",
"Sinaloa",
"Yucatán Peninsula",
"Quintana Roo",
"Cancún & Riviera Maya",
"Yucatán",
"Mérida",
"Nicaragua",
"Panama",
"South America",
"Argentina",
"Buenos Aires",
"Bolivia",
"Brazil",
"Central West Brazil",
"Brasilia",
"Goiás",
"Mato Grosso",
"Mato Grosso do Sul",
"North Brazil",
"Amazonas",
"Pará",
"Rondônia",
"Tocantins",
"Northeast Brazil",
"Alagoas",
"Bahia",
"Salvador",
"Ceará",
"Fortaleza",
"Maranhão",
"Paraíba",
"Pernambuco",
"Recife",
"Piauí",
"Rio Grande do Norte",
"Sergipe",
"South Brazil",
"Paraná",
"Rio Grande do Sul",
"Porto Alegre",
"Santa Catarina",
"Southeast Brazil",
"Espirito Santo",
"Minas Gerais",
"Belo Horizonte",
"Rio de Janeiro",
"São Paulo",
"Chile",
"Santiago",
"Colombia",
"Bogota",
"Ecuador",
"Galapagos Islands",
"Quito",
"French Guiana",
"Guyana",
"Paraguay",
"Peru",
"Lima",
"Suriname",
"Uruguay",
"Venezuela",
"Caracas",
"Middle East",
"North America",
"Bermuda",
"Canada",
"Atlantic Provinces",
"New Brunswick",
"Newfoundland & Labrador",
"Nova Scotia",
"Halifax",
"Prince Edward Island",
"British Columbia",
"Vancouver",
"Victoria (BC)",
"Canadian Prairies",
"Alberta",
"Calgary",
"Edmonton",
"Manitoba",
"Winnipeg",
"Saskatchewan",
"Northern Territories",
"Ontario",
"Greater Toronto",
"Hamilton-Niagara Peninsula",
"Ottawa-Gatineau",
"Southwestern Ontario",
"Quebec",
"Montreal",
"Quebec City",
"USA",
"Alaska",
"California",
"California Central Coast",
"Lake Tahoe",
"Sacramento Valley",
"San Francisco Bay Area",
"San Joaquin Valley",
"Silicon Valley",
"Southern California",
"Inland Empire",
"Los Angeles",
"Orange County (CA)",
"San Diego",
"Florida",
"Central Florida",
"Deltona-Daytona Beach",
"Greater Orlando",
"Tampa Bay Area",
"Florida Panhandle",
"Tallahassee",
"North Florida",
"Jacksonville",
"Southern Florida",
"Florida Keys",
"Fort Myers-Cape Coral",
"South Florida Metro",
"Broward-Fort Lauderdale",
"Miami-Dade",
"West Palm Beach-Boca Raton",
"Great Plains (USA)",
"Kansas",
"Nebraska",
"North Dakota",
"Oklahoma",
"Oklahoma City",
"Tulsa",
"South Dakota",
"Hawaii",
"Big Island (Hawaii)",
"Kauai",
"Maui",
"Oahu",
"Mid-Atlantic (USA)",
"Delaware",
"Maryland",
"Baltimore Metro",
"New Jersey",
"New York State",
"Albany-Capital District",
"Buffalo-Niagara Falls",
"New York City",
"Rochester-Finger Lakes",
"Pennsylvania",
"Harrisburg-South Central PA",
"Philadelphia",
"Pittsburgh",
"Washington DC",
"Midwest (USA)",
"Illinois",
"Chicago",
"Indiana",
"Indianapolis",
"Iowa",
"Michigan",
"Detroit",
"Grand Rapids-West Michigan",
"Minnesota",
"Minneapolis-Saint Paul",
"Missouri",
"Greater St. Louis",
"Kansas City",
"Ohio",
"Cincinnati",
"Columbus (OH)",
"Greater Cleveland",
"Wisconsin",
"Milwaukee",
"New England",
"Connecticut",
"Greater Hartford",
"New Haven",
"Maine",
"Massachusetts",
"Boston Metro",
"New Hampshire",
"Rhode Island",
"Providence",
"Vermont",
"Pacific Northwest",
"Oregon",
"Portland (OR)",
"Washington State",
"Seattle-Tacoma",
"Rocky Mountains",
"Colorado",
"Denver",
"Idaho",
"Montana",
"Wyoming",
"South (USA)",
"Alabama",
"Birmingham (AL)",
"Arkansas",
"Georgia (USA)",
"Atlanta",
"Kentucky",
"Louisville",
"Louisiana",
"Baton Rouge",
"New Orleans",
"Mississippi",
"North Carolina",
"Charlotte Metro",
"Piedmont Triad",
"Raleigh-Durham",
"South Carolina",
"Greater Charleston (SC)",
"Myrtle Beach & Grand Strand",
"Upstate South Carolina",
"Tennessee",
"Memphis",
"Nashville",
"Virginia",
"Richmond-Petersburg",
"Virginia Beach-Hampton Roads",
"West Virginia",
"Southwest (USA)",
"Arizona",
"Phoenix",
"Tucson",
"Nevada",
"Las Vegas",
"Reno-Sparks",
"New Mexico",
"New Albuquerque-Santa Fe",
"Utah",
"Salt Lake City",
"Texas",
"Austin-Round Rock",
"Dallas-Fort Worth",
"El Paso",
"Houston",
"San Antonio",
"Oceania",
"Australia",
"New South Wales",
"Canberra",
"Newcastle (AU)",
"Sydney",
"Northern Territory",
"Queensland",
"Brisbane",
"Cairns",
"Gold Coast",
"South Australia",
"South Adelaide",
"Tasmania",
"Victoria (AU)",
"Melbourne",
"Western Australia",
"Western Perth",
"New Zealand",
"Auckland",
"Christchurch",
"Wellington",
"Pacific Islands",
"Melanesia",
"Fiji",
"Papua New Guinea",
"Micronesia",
"Guam",
"Polynesia",
"Tahiti & Bora Bora",
"Polar Regions");
